name: Build image on push or PR
on: ["push", "pull_request"]

jobs:
    build:

        runs-on: ubuntu-20.04
        
        steps:
        
        - uses: actions/checkout@v1

        - name: Dependencies
          run: |
              sudo sed -i 's/focal/hirsute/g' /etc/apt/sources.list
              sudo apt update
              sudo apt -y dist-upgrade
              sudo apt install binfmt-support qemu-user-static quilt debootstrap

        -
          name: Available platforms
          run: echo ${{ steps.qemu.outputs.platforms }}

        - name: Set image name
          run: |
              UMBREL_OS_VERSION="$(git describe --tags)"
              IMAGE_NAME="umbrel-os-${UMBREL_OS_VERSION}"
              echo "UMBREL_OS_VERSION=$UMBREL_OS_VERSION"  >> $GITHUB_ENV
              echo "IMAGE_NAME=$IMAGE_NAME"  >> $GITHUB_ENV

        - name: Run build script
          run: |
              echo "Building $IMAGE_NAME"
              sudo docker system prune --all --force
              sudo IMG_FILENAME=$IMAGE_NAME ZIP_FILENAME=$IMAGE_NAME UMBREL_OS_VERSION=$UMBREL_OS_VERSION ./build.sh

        - name: Copy ZIP to current working dir
          run: cp deploy/*.zip ./

        - name: Debug current working dir
          run: ls -la

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            path: ${{ env.IMAGE_NAME }}.zip
            name: ${{ env.IMAGE_NAME }}.zip
